version: "3.7"

volumes:
  postgres-data:
    driver: local

services:
  db:
    container_name: litefarm-db
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pg-litefarm
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    container_name: litefarm-api
    build:
      context: ./packages/api
      dockerfile: prod.Dockerfile
    ports:
      - "5000:5000"
    environment:
      WAIT_HOSTS: litefarm-db:5432
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/pg-litefarm
  frontend:
    container_name: litefarm-web
    build:
      context: ./packages/webapp
      dockerfile: prod.Dockerfile
    ports:
      - "80:80"
